apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: kafkasql-journal
  labels:
    strimzi.io/cluster: kafka-staging
spec:
  partitions: 3
  replicas: 3
  config:
    cleanup.policy: compact