apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: "file-customers"
  labels:
    strimzi.io/cluster: kafka-connect-staging
spec:
  class: org.apache.kafka.connect.file.FileStreamSinkConnector
  tasksMax: 1
  config:
    file: /tmp/file-customers.txt
    tasks.max: "1"
    topics: conn-simple.inventory.customers