apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-staging
spec:
  kafka:  
    jmxOptions: {}
    version: 3.7.0
    replicas: 3
    logging:
      type: inline
      loggers:
        kafka.root.logger.level: INFO
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
    config:
      auto.create.topics.enable: false
      auto.delete.topics.enable: false
      delete.topic.enable: true
      group.initial.rebalance.delay.ms: 8000
      default.replication.factor: 3
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      min.insync.replicas: 2
      num.partitions: 3
      log.message.format.version: "3.7"
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: kafka-metrics-config.yml
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 20Gi
        deleteClaim: false
    resources:
      limits:
        memory: 1G
        cpu: '1'
      requests:
        cpu: '200m'
        memory: 200Mi
    readinessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    livenessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
  zookeeper:
    config:
      autopurge.purgeInterval: 24
      autopurge.snapRetainCount: 3
      initLimit: 10
      syncLimit: 5
      timeTick: 2000
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: zookeeper-metrics-config.yml        
    replicas: 3
    logging: 
      type: inline
      loggers:
        zookeeper.root.logger: INFO
    resources:
      limits:
        memory: 1G
        cpu: '1'
      requests:
        cpu: '200m'
        memory: 200Mi    
    storage:
      type: persistent-claim
      size: 15Gi
      deleteClaim: false
  kafkaExporter:
    enableSaramaLogging: false
    resources:
      requests:
        cpu: 200m
        memory: 64Mi
      limits:
        cpu: 500m
        memory: 128Mi
    topicRegex: ".*"
    groupRegex: ".*"
    logging: error
  entityOperator:
    tlsSidecar:
      resources:
        requests:
          cpu: 200m
          memory: 96Mi
        limits:
          cpu: 500m
          memory: 128Mi
    topicOperator:
      logging:
        type: inline
        loggers:
          rootLogger.level: "INFO"
      reconciliationIntervalSeconds: 60
      jvmOptions:
        -Xms: 256m
        -Xmx: 256m
      resources:
        limits:
          cpu: 500m
          memory: 500Mi
        requests:
          cpu: 150m
          memory: 384Mi
    userOperator:   
      logging:
        type: inline
        loggers:
          rootLogger.level: "DEBUG"
          loggers: uop,informer
          logger.uop.name: io.strimzi.operator.user
          logger.uop.level: DEBUG
          logger.informer.name: io.fabric8.kubernetes.client.informers.impl
          logger.informer.level: DEBUG
      reconciliationIntervalSeconds: 60
      jvmOptions:
        -Xms: 256m
        -Xmx: 256m
      resources:
        limits:
          cpu: 500m
          memory: 500Mi
        requests:
          cpu: 150m
          memory: 384Mi
  clusterCa:
    renewalDays: 60
    validityDays: 3650
    generateCertificateAuthority: true
  clientsCa:
    renewalDays: 60
    validityDays: 3650
    generateCertificateAuthority: true
