apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: go-app
  name: go-app-deployment
  namespace: kafka 
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
        - args:
            - |
              while true; do
                sleep 3600;
              done
          command:
            - /bin/sh
            - -c
          image: golang:1.22-alpine
          imagePullPolicy: IfNotPresent
          name: go-app-container
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "500m"
              memory: "500Mi"
