apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: debezium-connect-cluster
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  version: 3.7.0
  replicas: 1
  bootstrapServers: kafka-staging-kafka-bootstrap.kafka.svc.cluster.local:9093
  tls:
    trustedCertificates:
      - secretName: kafka-staging-cluster-ca-cert
        certificate: ca.crt
  authentication:
    type: tls
    certificateAndKey:
      secretName: ap-internal-connect
      certificate: user.crt
      key: user.key
  metricsConfig:
    type: jmxPrometheusExporter
    valueFrom:
      configMapKeyRef:
        name: connect-metrics
        key: metrics-config.yml
  config:
    group.id: ap-con-cluster
    offset.storage.topic: ap-con-cluster-offsets
    config.storage.topic: ap-con-cluster-configs
    status.storage.topic: ap-con-cluster-status
    config.storage.replication.factor: -1
    offset.storage.replication.factor: -1
    status.storage.replication.factor: -1
    config.providers: env
    config.providers.env.class: org.apache.kafka.common.config.provider.EnvVarConfigProvider
  build:
    output:
      type: docker
      image: 172.19.0.7:5000/debezium:v0.9 
    plugins:
      - name: debezium-postgresql-connector
        artifacts:
          - type: tgz
            url: https://repo1.maven.org/maven2/io/debezium/debezium-connector-postgres/2.6.1.Final/debezium-connector-postgres-2.6.1.Final-plugin.tar.gz
