apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: ap-con-cluster-configs
  labels:
    strimzi.io/cluster: kafka-staging
spec:
  partitions: 1
  replicas: 3
  config:
    min.insync.replicas: 1
    cleanup.policy: compact
    retention.ms: 619200000
    segment.bytes: 1073741824
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: ap-con-cluster-status
  labels:
    strimzi.io/cluster: kafka-staging
spec:
  partitions: 5
  replicas: 3
  config:
    cleanup.policy: compact
    min.insync.replicas: 1
    retention.ms: 619200000
    segment.bytes: 1073741824
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: ap-con-cluster-offsets
  labels:
    strimzi.io/cluster: kafka-staging
spec:
  partitions: 25
  replicas: 3
  config:
    cleanup.policy: compact
    min.insync.replicas: 1
    retention.ms: 619200000
    segment.bytes: 1073741824