apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: kafka-simple
  name: service-reader
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-services
  namespace: kafka-simple
subjects:
- kind: ServiceAccount
  name: default
  namespace: kafka-simple
roleRef:
  kind: Role
  name: service-reader
  apiGroup: rbac.authorization.k8s.io 