kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafka-ui
  labels:
    app: kafka-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui
  template:
    metadata:
      labels:
        app: kafka-ui
    spec:
      containers:
        - name: kafka-ui
          image: provectuslabs/kafka-ui
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "1G"
              cpu: "800m"
          volumeMounts:
            - name: kafka-truststore
              readOnly: true
              mountPath: /opt/cert
            - name: client-keystore
              readOnly: true
              mountPath: /opt/certs
          ports:
            - name: http-port
              containerPort: 8081
              protocol: TCP
          env:
            - name: SERVER_PORT
              value: '8081'          
            - name: KAFKA_CLUSTERS_0_NAME
              value: kafka-cluster
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: "kafka-staging-kafka-bootstrap.kafka.svc.cluster.local:9093"
            - name: KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL
              value: SSL
            - name: KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_LOCATION
              value: /opt/cert/ca.p12
            - name: KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kafka-staging-cluster-ca-cert
                  key: ca.password
            - name: KAFKA_CLUSTERS_0_PROPERTIES_SSL_KEYSTORE_LOCATION
              value: /opt/certs/user.p12
            - name: KAFKA_CLUSTERS_0_PROPERTIES_SSL_KEYSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ap-internal-kafka-ui
                  key: user.password
            - name: KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME
              value: kafka-connect-staging
            - name: KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS
              value: "http://kafka-connect-staging-connect-api.kafka.svc.cluster.local:8083"
            - name: DYNAMIC_CONFIG_ENABLED
              value: 'true'
            - name: KAFKA_CLUSTERS_0_SCHEMAREGISTRY
              value: "http://apicurioregistry-service.kafka.svc.cluster.local:8080/apis/registry/v2" #/apis/ccompat/v7"
      volumes:
        - name: kafka-truststore
          secret:
            secretName: kafka-staging-cluster-ca-cert
            defaultMode: 420
        - name: client-keystore
          secret:
            secretName: ap-internal-kafka-ui
            defaultMode: 420            
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-ui
  labels:
    app: kafka-ui
spec:
  selector:
    app: kafka-ui
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
