apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: conn-cluster-configs
  labels:
    strimzi.io/cluster: kafka-staging
spec:
  partitions: 1
  replicas: 3
  config:
    min.insync.replicas: 1
    cleanup.policy: compact
    retention.ms: 619200000
    segment.bytes: 1073741824
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: conn-cluster-status
  labels:
    strimzi.io/cluster: kafka-staging
spec:
  partitions: 5
  replicas: 3
  config:
    cleanup.policy: compact
    min.insync.replicas: 1
    retention.ms: 619200000
    segment.bytes: 1073741824
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: conn-cluster-offsets
  labels:
    strimzi.io/cluster: kafka-staging
spec:
  partitions: 25
  replicas: 3
  config:
    cleanup.policy: compact
    min.insync.replicas: 1
    retention.ms: 619200000
    segment.bytes: 1073741824
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: internal-connect
  labels:
    strimzi.io/cluster: kafka-staging
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
    # Kafka Connects internal topics used to store configuration, offsets or status
    - resource:
        type: group
        name: conn-cluster
      operations:
        - Read
    - resource:
        type: topic
        name: conn-cluster-configs
      operations:
        - Read
        - Describe
        - Write
        - Create
    - resource:
        type: topic
        name: conn-cluster-status
      operations:
        - Read
        - Describe
        - Write
        - Create
    - resource:
        type: topic
        name: conn-cluster-offsets
      operations:
        - Read
        - Describe
        - Write
        - Create
      # Additional topics and groups used by connectors
    # Change to match the topics used by your connectors
    - resource:
        type: group
        name: ap-con-
        patternType: prefix
      operations:
        - Read
    - resource:
        type: group
        name: connect
        patternType: prefix
      operations:
        - Read
        - Describe
        - Write
        - Create
    - resource:
        type: topic
        name: ap-con-
        patternType: prefix
      operations:
        - Read
        - Describe
        - Write
        - Create
    - resource:
        type: topic
        name: __debezium-heartbeat.ap-con-debezium-test
      operations:
        - Read
        - Describe
        - Write
        - Create
